/*
 * MQTT 5 Reason Codes
 * All reason codes defined in MQTT 5.0 specification
 */

#ifndef CORE_MQTT5_REASON_CODES_H
#define CORE_MQTT5_REASON_CODES_H

/**
 * @brief MQTT 5 Reason Codes
 */
typedef enum MQTT5ReasonCode
{
    /* Success codes */
    MQTT5_REASON_SUCCESS = 0x00,
    MQTT5_REASON_NORMAL_DISCONNECTION = 0x00,
    MQTT5_REASON_GRANTED_QOS0 = 0x00,
    MQTT5_REASON_GRANTED_QOS1 = 0x01,
    MQTT5_REASON_GRANTED_QOS2 = 0x02,
    MQTT5_REASON_DISCONNECT_WITH_WILL = 0x04,
    MQTT5_REASON_NO_MATCHING_SUBSCRIBERS = 0x10,
    MQTT5_REASON_NO_SUBSCRIPTION_EXISTED = 0x11,
    MQTT5_REASON_CONTINUE_AUTHENTICATION = 0x18,
    MQTT5_REASON_REAUTHENTICATE = 0x19,
    
    /* Error codes */
    MQTT5_REASON_UNSPECIFIED_ERROR = 0x80,
    MQTT5_REASON_MALFORMED_PACKET = 0x81,
    MQTT5_REASON_PROTOCOL_ERROR = 0x82,
    MQTT5_REASON_IMPLEMENTATION_SPECIFIC_ERROR = 0x83,
    MQTT5_REASON_UNSUPPORTED_PROTOCOL_VERSION = 0x84,
    MQTT5_REASON_CLIENT_IDENTIFIER_NOT_VALID = 0x85,
    MQTT5_REASON_BAD_USERNAME_OR_PASSWORD = 0x86,
    MQTT5_REASON_NOT_AUTHORIZED = 0x87,
    MQTT5_REASON_SERVER_UNAVAILABLE = 0x88,
    MQTT5_REASON_SERVER_BUSY = 0x89,
    MQTT5_REASON_BANNED = 0x8A,
    MQTT5_REASON_SERVER_SHUTTING_DOWN = 0x8B,
    MQTT5_REASON_BAD_AUTHENTICATION_METHOD = 0x8C,
    MQTT5_REASON_KEEP_ALIVE_TIMEOUT = 0x8D,
    MQTT5_REASON_SESSION_TAKEN_OVER = 0x8E,
    MQTT5_REASON_TOPIC_FILTER_INVALID = 0x8F,
    MQTT5_REASON_TOPIC_NAME_INVALID = 0x90,
    MQTT5_REASON_PACKET_IDENTIFIER_IN_USE = 0x91,
    MQTT5_REASON_PACKET_IDENTIFIER_NOT_FOUND = 0x92,
    MQTT5_REASON_RECEIVE_MAXIMUM_EXCEEDED = 0x93,
    MQTT5_REASON_TOPIC_ALIAS_INVALID = 0x94,
    MQTT5_REASON_PACKET_TOO_LARGE = 0x95,
    MQTT5_REASON_MESSAGE_RATE_TOO_HIGH = 0x96,
    MQTT5_REASON_QUOTA_EXCEEDED = 0x97,
    MQTT5_REASON_ADMINISTRATIVE_ACTION = 0x98,
    MQTT5_REASON_PAYLOAD_FORMAT_INVALID = 0x99,
    MQTT5_REASON_RETAIN_NOT_SUPPORTED = 0x9A,
    MQTT5_REASON_QOS_NOT_SUPPORTED = 0x9B,
    MQTT5_REASON_USE_ANOTHER_SERVER = 0x9C,
    MQTT5_REASON_SERVER_MOVED = 0x9D,
    MQTT5_REASON_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED = 0x9E,
    MQTT5_REASON_CONNECTION_RATE_EXCEEDED = 0x9F,
    MQTT5_REASON_MAXIMUM_CONNECT_TIME = 0xA0,
    MQTT5_REASON_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED = 0xA1,
    MQTT5_REASON_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED = 0xA2
} MQTT5ReasonCode_t;

/**
 * @brief Check if reason code indicates success
 */
static inline bool MQTT5_IsSuccessReasonCode( uint8_t reasonCode )
{
    return ( reasonCode < 0x80U );
}

/**
 * @brief Check if reason code indicates error
 */
static inline bool MQTT5_IsErrorReasonCode( uint8_t reasonCode )
{
    return ( reasonCode >= 0x80U );
}

#endif /* CORE_MQTT5_REASON_CODES_H */
